set(CMAKE_SYSTEM_NAME Linux)
set(TOOL_CHAIN_PREFIX aarch64-himix100-linux)
set(CMAKE_C_COMPILER ${TOOL_CHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOL_CHAIN_PREFIX}-g++)

set(CMAKE_FIND_ROOT_PATH /opt/hisi-linux/x86-arm/aarch64-himix100-linux/aarch64-linux-gnu /usr/local)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

